services:
  vestilo_api:
    build: .
    container_name: vestilo_api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}" # Toma el 3200 de tu .env automáticamente
    env_file:
      - .env
    networks:
      - red_base_de_datos

networks:
  red_base_de_datos:
    external: true
    name: admivida-server_admivida_net